### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by iPersevere** [zhaobenx/Image-stitcher#6]
Hello, I'v got this issue when I reproduce your code. Could you please tell how solve it? Thank you
Traceback (most recent call last):
  File "E:/TensorFlow/TensorFlowCode/Image&Computer Vision/Image-stitcher-master/py/main.py", line 7, in <module>
    from stitch import Stitcher, Method
  File "E:\TensorFlow\TensorFlowCode\Image&Computer Vision\Image-stitcher-master\py\stitch.py", line 69
    self._keypoints1: List[cv2.KeyPoint] = None
                    ^
SyntaxError: invalid syntax

**Comment by zhaobenx** [comment]
This is python type hints. You can either delete the `: List[cv2.KeyPoint]` or  update your python to 3.5 or higher version.
Duplicated to #3 #4.
